language: r
cache: packages

os: 
  - osx
  - linux

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/beastier
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling

before_script:
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint
  - # No local files created
  - egrep -oR "\"~" --include={*.R,*.Rmd}
  - if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi
  - # Do a CRAN build
  - cd scripts; ./build_cran

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - travis_wait 20 Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
