language: r
cache: packages

matrix:
  include:
  - r: release
    os: linux
    env: INSTALL_BEAST2=true
  - r: devel
    os: linux
    env: INSTALL_BEAST2=false

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_install:
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  - sudo $(which R) CMD javareconf
  # libgit2-dev
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libgit2-dev; fi

before_script:
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  # PDF
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr update --self; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install inconsolata; fi
  # Lapack
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install liblapack-dev; fi
  # Install BEAST2
  - if [[ "$INSTALL_BEAST2" == true ]]; then Rscript -e 'remotes::install_github("richelbilderbeek/beastierinstall")'; fi
  - if [[ "$INSTALL_BEAST2" == true ]]; then Rscript -e 'beastierinstall::install_beast2()'; fi
  # Install BEAST2 NS package
  - if [[ "$INSTALL_BEAST2" == true ]]; then Rscript -e 'remotes::install_github("richelbilderbeek/mauricerinstall")'; fi
  - if [[ "$INSTALL_BEAST2" == true ]]; then Rscript -e 'mauricerinstall::install_beast2_package("ns")'; fi
  # lintr
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo pip install proselint; fi

after_success:
  # Codecov
  - if [[ "$INSTALL_BEAST2" == true ]]; then travis_wait 20 Rscript -e 'covr::codecov()'; fi
  # Goodpractice
  - if [[ "$INSTALL_BEAST2" == true ]]; then travis_wait 60 Rscript -e 'goodpractice::gp()'; fi
  # Lintr
  - if [[ "$INSTALL_BEAST2" == false ]]; then Rscript -e 'lintr::lint_package()'; fi
  # Proselint
  - if [[ "$INSTALL_BEAST2" == false ]]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi

