language: r
cache: packages

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
    #osx_image: xcode9.2

r_packages:
  - tracerer

r_github_packages:
  - richelbilderbeek/beautier
  - richelbilderbeek/beastier
  - jimhester/covr
  - jimhester/lintr
  - ropensci/spelling

before_install:
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  - sudo $(which R) CMD javareconf

before_script:
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  # PDF
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr update --self; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install inconsolata; fi
  # Lapack
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install liblapack-dev; fi
  # BEAST2. mauricer must work with and without BEAST2 installed
  - Rscript -e "beastier::install_beast2()"
  # Do not install BEAST2 NS package, won't work anyways
  # - Rscript -e "source(\"R/install_beast2_pkg.R\"); source(\"R/is_beast2_pkg_installed.R\"); source(\"R/get_beast2_pkg_names.R\"); install_beast2_pkg(\"NS\")"
  # lintr
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo pip install proselint; fi

after_success:
  # Lint
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then Rscript -e 'lintr::lint_package()'; fi
  # Codecov
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "devel" ]; then travis_wait 20 Rscript -e 'covr::codecov()'; fi
  # Proselint
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  # Goodpractice
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then travis_wait 60 Rscript -e 'goodpractice::gp()'; fi
  # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi
  - # Do a CRAN build
  - cd scripts; sh -x build_cran
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

after_failure:
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

