language: r
dist: xenial
cache: packages

r_packages:
  - xml2

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - ropensci/beastier
  - ropensci/tracerer@develop
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  - # if Linux, show distro
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/version; fi
  - # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  - # BEAST2
  - Rscript -e "beastier::install_beast2()"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint

after_success:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then Rscript -e "lintr::lint_package()"; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then Rscript -e "covr::codecov()"; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then travis_wait 20 Rscript -e "goodpractice::gp()"; fi
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  - # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi
  - # Do a CRAN build
  - cd scripts; sh -x build_cran
