language: r
cache: packages

r_packages:
  - devtools

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - ropensci/beastier
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  - # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  - # Java 8
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq oracle-java8-installer; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install oracle-java8-set-default; fi
  - # BEAST2
  - Rscript -e "beastier::install_beast2()"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint

after_success:
  - Rscript -e "lintr::lint_package()"
  - Rscript -e "covr::codecov()"
  - travis_wait 20 Rscript -e "goodpractice::gp()"
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  - # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi
  - # Do a CRAN build
  - cd scripts; sh -x build_cran
